### ISSUE TITLE
Bug:  at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)

### ISSUE THREAD

**Issue by eduardorcosta** [alexa-games/skill-flow-builder#41]
# Bug Report

## Skill Flow Builder Version
2.1.0

## ASK CLI Version
2.22.4

## Current Behavior
SFB won't install

## Expected Behavior
Should install

## Steps to Reproduce
Follow exact steps on https://github.com/alexa-games/skill-flow-builder

## Operating System
Mac OS Big Sur

## Node Version
15.12.0

```javascript
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.12.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build-modules'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v15.12.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Volumes/User/Development/Alexa/Historia/skill-flow-builder/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/eduardorochacosta/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 verbose npm-session 94cbe37e6edb7a91
20 timing npm:load Completed in 18ms
21 timing command:run Completed in 310418ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:369:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose pkgid sfb-skill-package@1.0.0
24 verbose cwd /Volumes/User/Development/Alexa/Historia/skill-flow-builder
25 verbose Darwin 20.3.0
26 verbose argv "/usr/local/Cellar/node/15.12.0/bin/node" "/usr/local/bin/npm" "run" "build-modules"
27 verbose node v15.12.0
28 verbose npm  v7.6.3
29 error code 1
30 error path /Volumes/User/Development/Alexa/Historia/skill-flow-builder
31 error command failed
32 error command sh -c cd packages && node buildAll -c
33 verbose exit 1
```

**Comment by anfazio** [comment]
Sorry for the delay here. We thought this might be related to another issue with the editor build, but this appears to be because you are using Node 15, and Skill Flow Builder hasn't been updated to support v15 yet. Please try building with Node 14 instead.

**Comment by tyliec** [comment]
Noting that a lot of the errors seem associated with the `sfb-editor` package, specifically the `AceEditor` component. The build issue with Node 15 might be fixed if the generated files are just swapped out for their updated versions.
