### ISSUE TITLE
Bug: yarn install fails when installing SFB

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa-games/skill-flow-builder#53]
# Bug Report

## Skill Flow Builder Version
v2.0.0

## ASK CLI Version
v2.24.1

## Current Behavior
Error when running `yarn install`

## Expected Behavior
SFB build completes successfully and I am able to start the editor.

## Steps to Reproduce
1. Download skill-flow-builder as a ZIP
2. Unzip into a folder
3. Open Bash Shell in VSCode to `skill-flow-builder-master` folder
4. Execute `yarn install`
5. Get the following log that includes errors for building `sfb-cli` and `sfb-editor`:

```
$ yarn install
yarn install v1.22.11
warning package.json: License should be a valid SPDX license expression
warning sfb-skill-package@1.0.0: License should be a valid SPDX license expression
[1/4] Resolving packages...
success Already up-to-date.
$ npm run build-modules

> sfb-skill-package@1.0.0 build-modules C:\dev\skill-flow-builder\skill-flow-builder-master
> cd packages && node buildAll -c

  sfb-util: Cleaning......
✔ sfb-util: Clean finished in 1615 ms.
  sfb-polly: Cleaning......
✔ sfb-polly: Clean finished in 1643 ms.
  sfb-f: Cleaning......
✔ sfb-f: Clean finished in 1698 ms.
  sfb-test: Cleaning......
✔ sfb-test: Clean finished in 1630 ms.
  sfb-skill: Cleaning......
✔ sfb-skill: Clean finished in 2162 ms.
  sfb-vscode-extension: Cleaning......
✔ sfb-vscode-extension: Clean finished in 2008 ms.
  sfb-story-debugger: Cleaning......
✔ sfb-story-debugger: Clean finished in 1698 ms.
  sfb-cli: Cleaning......
✔ sfb-cli: Clean finished in 3726 ms.
  sfb-editor: Cleaning......
✔ sfb-editor: Clean finished in 19084 ms.
Finished in 35280 ms.
  sfb-util: Building......
✔ sfb-util: Build finished in 26592 ms.
  sfb-polly: Building......
✔ sfb-polly: Build finished in 42678 ms.
  sfb-f: Building......
✔ sfb-f: Build finished in 55443 ms.
  sfb-test: Building......
✔ sfb-test: Build finished in 39356 ms.
  sfb-skill: Building......
✔ sfb-skill: Build finished in 44574 ms.
  sfb-vscode-extension: Building......
✔ sfb-vscode-extension: Build finished in 48690 ms.
  sfb-story-debugger: Building......
✔ sfb-story-debugger: Build finished in 49358 ms.
  sfb-cli: Building......
✘ sfb-cli: Build failed.
  sfb-editor: Building......
✘ sfb-editor: Build failed.
Finished in 523881 ms.
There were failures: sfb-cli,sfb-editor
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sfb-skill-package@1.0.0 build-modules: `cd packages && node buildAll -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sfb-skill-package@1.0.0 build-modules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mark\AppData\Roaming\npm-cache\_logs\2021-09-13T02_07_17_243Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Operating System
Windows 10

## Node Version
node - v14.17.6
npm  - v6.14.15

```javascript
// code samples
```

**Comment by shikida** [comment]
same here. very frustrating.
node 16.13.1
ubuntu 20.04.3

**Comment by shikida** [comment]
npm 8.3.0

**Comment by jmbouffa** [comment]
Same. Any update on this?

**Comment by winghavenrc** [comment]
Ditto... so, does Amazon support this or not?

**Comment by jheym** [comment]
anyone figure out a workaround yet? Having the same issue. Tried building on windows and ubuntu and getting the same results. 

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build-modules' ]
2 info using npm@6.14.12
3 info using node@v10.24.1
4 verbose run-script [ 'prebuild-modules', 'build-modules', 'postbuild-modules' ]
5 info lifecycle sfb-skill-package@1.0.0~prebuild-modules: sfb-skill-package@1.0.0
6 info lifecycle sfb-skill-package@1.0.0~build-modules: sfb-skill-package@1.0.0
7 warn lifecycle The node binary used for scripts is /tmp/yarn--1665217176429-0.4982328757904708/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle sfb-skill-package@1.0.0~build-modules: unsafe-perm in lifecycle true
9 verbose lifecycle sfb-skill-package@1.0.0~build-modules: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/di0x0ib/skill-flow-builder/node_modules/.bin:/tmp/yarn--1665217176429-0.4982328757904708:/home/di0x0ib/skill-flow-builder/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/usr/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle sfb-skill-package@1.0.0~build-modules: CWD: /home/di0x0ib/skill-flow-builder
11 silly lifecycle sfb-skill-package@1.0.0~build-modules: Args: [ '-c', 'cd packages && node buildAll -c' ]
12 silly lifecycle sfb-skill-package@1.0.0~build-modules: Returned: code: 1  signal: null
13 info lifecycle sfb-skill-package@1.0.0~build-modules: Failed to exec build-modules script
14 verbose stack Error: sfb-skill-package@1.0.0 build-modules: `cd packages && node buildAll -c`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid sfb-skill-package@1.0.0
16 verbose cwd /home/di0x0ib/skill-flow-builder
17 verbose Linux 5.15.0-48-generic
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build-modules"
19 verbose node v10.24.1
20 verbose npm  v6.14.12
21 error code ELIFECYCLE
22 error errno 1
23 error sfb-skill-package@1.0.0 build-modules: `cd packages && node buildAll -c`
23 error Exit status 1
24 error Failed at the sfb-skill-package@1.0.0 build-modules script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`
